#!/usr/bin/env bash

# go back to where we were invoked
cd "$CWD"

save_and_shutdown() {
  # force clean shutdown
  halt -f
}

# make sure we shut down cleanly
trap save_and_shutdown EXIT INT TERM

# configure path to include /usr/local
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# can't do much without proc!
mount -t proc none "/proc"

# pseudo-terminal devices
mkdir -p "/dev/pts"
mount -t devpts none "/dev/pts"

# shared memory a good idea
mkdir -p "/dev/shm"
mount -t tmpfs none "/dev/shm"

# sysfs a good idea
mount -t sysfs none "/sys"

# pidfiles and such like
mkdir -p "/var/run"
mount -t tmpfs none "/var/run"

# takes the pain out of cgroups
cgroups-mount

# var/lib storage for docker if accessible use the host directories
mkdir -p "/var/lib/docker"
if [ ! -w "/var/lib/docker" ]; then
	echo "/var/lib/docker is not writable, mounting temporary filesystem" > /dev/stderr
	mount -t tmpfs -o size=8g tmpfs "/var/lib/docker"
fi

# etc storage for docker if accessible use the host directories
mkdir -p "/etc/docker"
if [ ! -w "/etc/docker" ]; then
	echo "/etc/docker is not writable, mounting temporary filesystem" > /dev/stderr
	mount -t tmpfs -o size=10m tmpfs "/etc/docker"
fi

export DOCKER_CERT_PATH=/var/lib/docker

# mount logdir if existing
if [ "$LOGDIR" ]; then
	mount -t hostfs -o "$LOGDIR" none "/var/log"
fi

# configure networking
ip addr add 127.0.0.1 dev lo
ip link set lo up
ip addr add 10.1.1.1/24 dev eth0
ip link set eth0 up
ip route add default via 10.1.1.254
echo "1" > "/proc/sys/net/ipv4/ip_forward"

# This is to handle when /etc/resolv.conf -> /run/resolvconf/resolv.conf
if [ -L "/etc/resolv.conf" ]; then
	mkdir -p "$(dirname "$(readlink --canonicalize-missing "/etc/resolv.conf")")"
	if [ ! -f "/etc/resolv.conf" ]; then
		cat "/var/log/resolv.conf" > "/etc/resolv.conf"
	fi
fi
[ -f "/var/log/stdout" ] && exec >> "/var/log/stdout"
[ -f "/var/log/stderr" ] && exec 2>> "/var/log/stderr"

# execute the command
/usr/bin/env sh -c "${CMD}"
# preserve commands exit code
echo "$?" > "/var/log/status"
